[retirejs."js_library_patterns_retirejs.json"]
source = "https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/jsrepository-master.json"
hash = "4"
timestamp = "2025-02-11T17:55:20.737210+00:00"
