[emba."native_lib_patterns_emba.json"]
source = "https://raw.githubusercontent.com/e-m-b-a/emba/11d6c281189c3a14fc56f243859b0bccccce8b9a/config/bin_version_strings.cfg"
hash = "2"
timestamp = "2025-02-11T18:28:54.186052+00:00"
