name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Build wheel
        run: |
          python -m build
      - name: Upload Python package dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-dist
          path: |
            dist

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build-wheel
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: release
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download Python package dist artifacts
      uses: actions/download-artifact@v3
      with:
        name: python-package-dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

